services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    command: gunicorn core.wsgi:application --reload --bind 0.0.0.0:8000
    env_file:
      - docker/.env
    restart: always
    depends_on:
      - db
    volumes:
      - ./project:/app
      - ./volumes/media:/media
      - ./volumes/static:/static

  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data/
    env_file:
      - docker/.env

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d
      - ./volumes/static:/var/www/static
      - ./volumes/media:/var/www/media
    depends_on:
      - app
    ports:
      - "80:80"